argus_stereo_sync:

  # Camera info params defaults to (empty) -- no camera info
  left_camera_info:
    type: string
    default_value: ""
    description: "URL to camera info file for left camera"

  right_camera_info:
    type: string
    default_value: ""
    description: "URL to camera info file for left camera"

  framerate:
    type: int
    default_value: 10
    description: "Frame rate (frames/sec)"
    validation:
      bounds<>: [1, 60]

  trigger_mode:
    type: string
    default_value: external
    description: "Camera trigger:  internal or external"
    validation:
      one_of<>: [["internal", "external",]]
